--- #YAML:1.0
name:               libnet
version:            1.22_01
abstract:           Collection of Network protocol modules
author:
    - Graham Barr <gbarr@pobox.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket:  1.05
    Socket:      1.3
resources:
    repository:  http://github.com/gbarr/perl-libnet
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
